export const ADD_TODO = 'ADD_TODO';

export const DELETE_TODO = 'DELETE_TODO';

export const DELETE_CHILD_TODO = 'DELETE_CHILD_TODO';

export const ADD_TODO_CHILD = 'ADD_TODO_CHILD';

export const COMPLETE_TODO = 'COMPLETE_TODO';

export const TOGGLE_TODO = 'COMPLETE_ALL_TODO';

export const STATUS_FILTER_BUTTON = 'STATUS_FILTER_BUTTON';

export const SAVE_TEXT_INPUT = 'SAVE_TEXT_INPUT';

export const SORT_TODO = 'SORT_TODO';

export const CLEAR_COMPLETE = 'CLEAR_COMPLETE';

export const GET_TODOS_REQUEST = 'GET_TODOS_REQUEST';

export const GET_TODOS_SUCCES = 'GET_TODOS_SUCCES';

export const GET_TODOS_FAILRE = 'GET_TDOS_FAILRE';

export const POST_TODO_REQUEST = 'POST_TODO_REQUEST';

export const POST_TODO_SUCCESS = 'POST_TODO_SUCCESS';

export const POST_TODO_FAILRE = 'POST_TODO_FAILRE';

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST';

export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';

export const DELETE_TODO_FAILRE = 'DELETE_TODO_FAILRE'; 

export const PUT_TODO_REQUEST = 'PUT_TODO_REQUEST';

export const PUT_TODO_SUCCESS = 'PUT_TODO_SUCCESS';

export const PUT_TODO_FAILRE = 'PUT_TODO_FAILRE';

export const ADD_TODO_CHILD_SUCCESS = 'ADD_TODO_CHILD_SUCCESS';

export const ADD_TODO_CHILD_FAILRE = 'ADD_TODO_CHILD_FAILRE';

export const TOGGLE_TODO_SUCCESS = 'TOGGLE_TODO_SUCCESS';

export const TOGGLE_TODO_FAILRE = 'TOGGLE_TODO_FAILRE';

export const TOGGLE_ALL = 'TOGGLE_ALL';

export const TOGGLE_ALL_SUCCESS = 'TOGGLE_ALL_SUCCESS';

export const TOGGLE_ALL_FAILRE = 'TOGGLE_ALL_FAILRE';