const ADD_TODO = 'ADD_TODO';
const DELETE_TODO = 'DELETE_TODO';
const DELETE_CHILD_TODO = 'DELETE_CHILD_TODO';
const ADD_TODO_CHILD = 'ADD_TODO_CHILD';
const COMPLETE_TODO = 'COMPLETE_TODO';
const TOGGLE_TODO = 'COMPLETE_ALL_TODO';
const STATUS_FILTER_BUTTON = 'STATUS_FILTER_BUTTON';

export {
    ADD_TODO,
    DELETE_TODO,
    DELETE_CHILD_TODO,
    ADD_TODO_CHILD,
    COMPLETE_TODO,
    TOGGLE_TODO,
    STATUS_FILTER_BUTTON
}